
title: "Newham's Blog"
description: > # this means to ignore newlines until "baseurl:"
  Love is Love!

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
src: "https://github.com/newham/newham.github.io"

author: 
  name : Liu Han
  email: newham.cn@gmail.com
  github: https://github.com/newham/

# Build settings
markdown: kramdown

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Pagination
paginate:           10
paginate_path:      /page/:num

plugins:
  - jekyll-paginate

page:
  categories: /categories/
  about: /about/
  index: /
