
title: "Newham's Blog"
description: > # this means to ignore newlines until "baseurl:"
  Love is Love!

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author: 
  name : Newham
  email: newham.cn@gmail.com

# Build settings
markdown: kramdown

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Pagination
paginate:           6
paginate_path:      /page:num/

gems:
  - jekyll-paginate

page:
  about: /about/
  index: /
